#resolver: lts-17.12
resolver: snapshot.yaml

packages:
- '.'

#extra-deps:
#- llvm-hs-12.0.0
#- llvm-hs-pure-12.0.0
#- llvm-hs-pretty-12.0.0

flags:
  llvm-hs:
    shared-llvm: true

ghc-options:
  llvm-hs: -optcxx=-std=c++14 -optcxx=-lstdc++ -optcxx=-fno-rtti
