#resolver: lts-16.31
resolver: snapshot.yaml

packages:
- '.'

extra-deps:
# Until a bug in GHC 8.10 is fixed, we cannot compile llvm-hs with GHC 8.10
# Unfortunately, all stackage snapshots after lts-16.31 use GHC 8.10
# Since the older snapshots we are forced to use have versions of these packages
# which are missing required functionality, we need to specify versions here.
- data-fix-0.3.1
- recursion-schemes-5.2.2.1
- th-abstraction-0.4.2.0
#- llvm-hs-12.0.0
#- llvm-hs-pure-12.0.0
#- llvm-hs-pretty-12.0.0

flags:
  llvm-hs:
    shared-llvm: true
